# Generated by Django 2.2.4 on 2019-09-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=' this is the best product in the whole town. if you dont want to buy go and fuck your self drained pussy bitch. but if you want to still buy product on our site, it is very easy and you are not an over grown bitch. well i am just tring somenew fucking crap so if you dont like it go fuck your mum with your dad!!! no offence!!'),
            preserve_default=False,
        ),
    ]
